name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NJ_SCRAPER_BUCKET_NAME: ${{ vars.NJ_SCRAPER_BUCKET_NAME }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Build
      run: |
        npm ci
        npm run lint
        npm run build
        npm run test
    - name: Migrate Tables
      run: |
        npx prisma migrate deploy
    - name: Deploy AWS Stack
      run: |
        set -euxo pipefail
        npx cdk bootstrap aws://${{secrets.AWS_ACCOUNT_ID}}/${{secrets.AWS_DEFAULT_REGION}}
        npx cdk deploy --require-approval never