name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        # your test command here
    - name: Test
      run: |
        # your test command here
    - name: Migrate Tables
      if: github.ref == 'refs/heads/dev'
      run: |
        npx prisma migrate dev