name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: |
        # your test command here
    - name: Migrate Tables
      if: github.ref == 'refs/heads/main'
      run: |
        npx prisma migrate dev
      env:
        DATABASE_URL: $DATABASE_URL