name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Migrate Tables
      if: github.ref == 'refs/heads/main'
      run: |
        npx prisma migrate dev
        