name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    steps:
    - env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Build
      run: |
        npm ci
        npm run build
    - name: Migrate Tables
      if: github.ref == 'refs/heads/main'
      run: |
        npx prisma migrate deploy
        